Try travis / SDK man

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,38 @@
 sudo: false
 dist: trusty
 language: scala
-jdk:
-  - oraclejdk8
-script: java -version && for v in openjdk11 oraclejdk11 openjdk8 oraclejdk8; do echo $v; (~/bin/install-jdk.sh --install $v --target $HOME/$v && $HOME/bin/java -version) || echo "not available"; done
+before_install:
+  - |
+    # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
+    [[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/
+    curl -sSL https://get.sdkman.io | bash
+    echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
+    echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
+    source $HOME/.sdkman/bin/sdkman-init.sh
+    sdkJava=$(sdk list java | grep -o " $ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1 | cut -c2-)
+    sdk install java $sdkJava || true # install fails if it's already installed
+    sdk use java $sdkJava
+    unset JAVA_HOME
+    if [[ $ADOPTOPENJDK == 8 ]]; then versionPrefix="1\.8"; else versionPrefix=$ADOPTOPENJDK; fi
+    java -version
+  - java -version 2>&1 | grep 'AdoptOpenJDK.*[^0-9]'$versionPrefix'[^0-9]' || exit 1
+
+before_cache:
+  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
+  - rm -fv $HOME/.sdkman/var/broadcast
+  - rm -fv $HOME/.sdkman/var/broadcast_id
+  - find $HOME/.ivy2/cache -name "ivydata-*.properties"     -print -delete
+  - find $HOME/.sbt        -name "*.lock"                   -print -delete
+  - find $HOME/.sbt        -name "*compiler-bridge_*-bin-*" -print -delete
+
+cache:
+  directories:
+    - $HOME/.ivy2/cache
+    - $HOME/.sbt
+    - $HOME/.sdkman
+    - $HOME/.cache/coursier
+env:
+  global:
+    - ADOPTOPENJDK=8
+
+script: java -version
